version: '3.8'
services:
  product-catalog-service:
    build: ./product-catalog-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/product_catalog_service
  user-auth-service:
    build: ./user-auth-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/user_auth_service